In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [3]:
dataset_path = "rockpaperscissors"
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)
train_generator = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical',
    subset='training',
)
validation_generator = train_datagen.flow_from_directory(
dataset_path,
target_size=(150, 150),
batch_size=32,
class_mode='categorical',
subset='validation',
)

Found 1751 images belonging to 3 classes.
Found 437 images belonging to 3 classes.


In [4]:
model = Sequential([
    Conv2D(32, (3,3), activation= 'relu', input_shape = (150,150,3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation= 'relu'),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation= 'relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(512,activation= 'relu'),
    Dense(3, activation= 'softmax')
])

model.summary()

c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 34, 34, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 17, 17, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 36992)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │    18,940,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │         1,539 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,035,203 (72.61 MB)

 Trainable params: 19,035,203 (72.61 MB)

 Non-trainable params: 0 (0.00 B)

In [5]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy'])

In [6]:
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10
)

Epoch 1/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 14s 220ms/step - accuracy: 0.7025 - loss: 0.8312 - val_accuracy: 0.8192 - val_loss: 0.4882
Epoch 2/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 12s 212ms/step - accuracy: 0.9001 - loss: 0.2991 - val_accuracy: 0.9268 - val_loss: 0.2128
Epoch 3/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 11s 204ms/step - accuracy: 0.9463 - loss: 0.1561 - val_accuracy: 0.9382 - val_loss: 0.1788
Epoch 4/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 13s 230ms/step - accuracy: 0.9674 - loss: 0.1031 - val_accuracy: 0.9497 - val_loss: 0.1469
Epoch 5/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 29s 528ms/step - accuracy: 0.9852 - loss: 0.0523 - val_accuracy: 0.9611 - val_loss: 0.1488
Epoch 6/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 41s 526ms/step - accuracy: 0.9886 - loss: 0.0359 - val_accuracy: 0.9703 - val_loss: 0.1046
Epoch 7/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 23s 414ms/step - accuracy: 0.9937 - loss: 0.0233 - val_accuracy: 0.9588 - val_loss: 0.1260
Epoch 8/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 12s 208ms/step - accuracy: 0.9954 - loss: 0.0130 - val_accu

In [7]:
val_loss, val_acc = model.evaluate(validation_generator)
print(f'Validation loss: {val_loss}, Validation accuracy: {val_acc}')

14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - accuracy: 0.9703 - loss: 0.1274
Validation loss: 0.12738782167434692, Validation accuracy: 0.970251739025116


In [8]:
predictions = model.predict(validation_generator)
print(predictions) # Output berupa probabilitas prediksi tiap kelas

14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step
[[1.4445530e-07 9.9999988e-01 1.6672811e-11]
 [3.8896713e-05 9.9996114e-01 9.3664614e-09]
 [9.9999654e-01 3.2011296e-06 1.9933262e-07]
 ...
 [1.2747335e-04 2.9585002e-12 9.9987257e-01]
 [1.0000000e+00 1.1907280e-14 3.5112468e-09]
 [4.8367741e-07 9.9999952e-01 5.9774104e-13]]
